server:
  port: 9090

constants:
  media-path: /data/media/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    header: "Authorization"
    key: jxgEQeXA28P32q8AVdbyk1ASDANdu8553YUn4

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    default-schema: public
    baseline-on-migrate: true
  application:
    name: user-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb: DEBUG
